### ISSUE TITLE
i fixed unityengine.networking.Types in 2022.3.7f1!!!!!!!

### ISSUE THREAD

**Issue by Epiczhul** [Games-For-Non-Gamers/Etras-Starter-Assets#21]
i fixed it, i only replaced unityengine.networking.Types with this:

using UnityEngine.Networking.PlayerConnection;
using System.Net.Cache;
using System.Net.NetworkInformation;
using System.Net.Mime;
using System.Net.Mail;
using System.Net.Http;
using System.Net.Security;
using System.Net.Sockets;
using System.Net.WebSockets
using UnityEngine.Networking;

and now i can run the game, walk, jump etc.

**Comment by perryhq** [comment]
Are you in the [discord](https://discord.gg/X8deyBDdTs)? If not, go there so there's no implementation problems and to help add this fix to the asset.

**Comment by Epiczhul** [comment]
@perrylets can not join. got banned for saying the github link is not under one of the two videos about etra's starter assets.
but it is not under the videos. whats your discord name?
