### ISSUE TITLE
Protect main branch from direct commits! >:c

### ISSUE THREAD

**Issue by Chizaruu** [Games-For-Non-Gamers/Etras-Starter-Assets#3]
There are several reasons why it is essential to protect the main branch from direct commits on GitHub:

1. **Ensuring stability:** The main branch is typically the default branch in a Git repository and should contain a stable project version. Direct commits to the main branch can introduce bugs or errors that can break the build or cause other issues.

2. **Enforcing code review:** By protecting the main branch, you can enforce a code review process where other collaborators review changes before merging. This helps ensure the code is high quality, meets coding standards, and is aligned with the project goals.

3. **Maintaining a clear history:** When changes are made to the main branch, it is crucial to maintain a clear history of the changes and why. By enforcing a pull request process, changes can be tracked more efficiently, and you can ensure that commit messages are informative and precise.
 
4. **Preventing accidental or malicious changes:** Protecting the main branch helps prevent accidental or malicious modifications that could significantly impact the project. For example, someone could accidentally delete essential files or make changes that are not in line with the project's goals.

Protecting the main branch helps ensure your project remains stable, high-quality, and aligned with your goals.

**Comment by sadkris** [comment]
Main branch *should* only be able to have commits from contributors

**Comment by sadkris** [comment]
Just checked with someone, non-contributors don't have write access. Appreciate the concern, though.
