### ISSUE TITLE
Please Add Assembly Definitions to the Scripts folder

### ISSUE THREAD

**Issue by Walter-Hulsebos** [Games-For-Non-Gamers/Etras-Starter-Assets#4]
I would like to request the addition of Assembly Definitions to the Scripts folder. 
As you may know, Assembly Definitions provide a way to organize code into logical groups that can be compiled separately, making it easier to manage large projects and speed up compilation. 

However, currently, the project does not make use of Assembly Definitions or Assembly References, which is an issue for users who rely on them in their workflows.

If you do that, I would advise turning on auto-referenced assembly mode. 
This mode automatically adds all the assembly definitions in the project to the references of each assembly that is built. 
Meaning that all code that _doesn't_ use assembly definitions still automatically has a reference to the code.

I hope you consider this request.
Thank you.

If you'd like I can even spend some time making a PR for you, but since you're using a Trello and such, I wouldn't want to intrude.

**Comment by Etra-Games** [comment]
I'd love any help you can offer :) 

Right now I have quite a few developers in Discord and I'd love to have you join. Making your PR won't conflict with the trello. We'd love to have you join.
https://discord.gg/jCAqXuHd

Here's a Devlog with links to tutorials if they help.
https://www.youtube.com/watch?v=athMUGbD0Ic

**Comment by perryhq** [comment]
Assembly definitions are in use!
