### ISSUE TITLE
Please Use Namespaces to Avoid Type Name Conflicts

### ISSUE THREAD

**Issue by Walter-Hulsebos** [Games-For-Non-Gamers/Etras-Starter-Assets#5]
Hello,

I would like to request that namespaces be used in the package.
You're currently not using your own namespaces, this can lead to some errors.
It is very possible that some of your scripts will have type names that conflict with those already in users' projects.

To avoid such conflicts, I suggest that namespaces be used to group related classes together and to prevent naming conflicts with external scripts. This will make it easier for users to manage their scripts and to avoid errors that may arise from duplicate type names.

This would be especially beneficial for beginners since they would most likely not be using namespaces and would maybe find it hard to solve those conflicts on their own accord.

Additionally, using namespaces will also make it easier for you developers to organize the package's code and to maintain it over time. It will make it easier to locate specific classes and to understand the relationships between different parts of the code.

I hope you consider this request and use namespaces in the project.

Thank you.

**Comment by Etra-Games** [comment]
I'd love any help you can offer :)

Right now I have quite a few developers in Discord and I'd love to have you join. Making your PR won't conflict with the trello. We'd love to have you join.
https://discord.gg/jCAqXuHd

Here's a Devlog with links to tutorials if they help.
https://www.youtube.com/watch?v=athMUGbD0Ic

**Comment by perryhq** [comment]
Namespaces are done!
